name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-ci:
    uses: argos-ai-xdr/argos-control/.github/workflows/reusable-python-ci.yaml@ba1b70900218ae56d4ca93ed1404ca1d341e137c
    with:
      working-directory: "."
      contracts-ref: "main"
    secrets: inherit
